### PR TITLE
Fallback buttons

### PR DESCRIPTION
**Pull request by BenAM63**
- Added Topic Tips Action with different responses based on the slot type. Buttons were also added with random topics
- Copied changes from Bob's recent synonym branch to get improved intent recognition, especially with "request_jobs"
- Added random buttons for topics, careers, and class codes
- Modified adjacent_fields as well as related stories and test stories to work with buttons rather than having the user write out a response
- Removed the topic tips utterances since those are covered by the new topic tips action
- Fixed some typos as I saw them

### CODE REVIEW

**Comment by rocaplin** [comment]
rasa-dev validate
There is an issue in rasa/data/stories.yml at line 224. Remove leading spaces in front of story:
  - story: action request class by code 2
\rightarrow→
- story: action request class by code 2

**Comment by BenAM63** [comment]
> rasa-dev validate There is an issue in rasa/data/stories.yml at line 224. Remove leading spaces in front of story:
> 
>     * story: action request class by code 2
>       \rightarrow→
> 
>     * story: action request class by code 2

My changes shouldn't have affected that line, and I didn't get a rasa-dev validate error when I tested just now.

**Comment by rocaplin** [comment]
My bad... I checked out the branch without pulling so I still had the code from the prior pull request.

**Comment by rocaplin** [comment]
It looks like some of the recovery technique stuff Scott added is getting deleted from the rules and domain files.

**Comment by BenAM63** [comment]
The recovery technique is performed using an action instead that handles the different slot options. So only one overall fallback rule is needed.

**Comment by BenAM63** [comment]
Note: There's a typo on line 16 of CS-Jobs.csv where it says "eveloper" instead of "developer".

**Review by scornaby-ufo — APPROVED** [review]

**Pull request merged**
