### PR TITLE
Redesigned webpage

### PR DESCRIPTION
**Pull request by kohara260**

### CODE REVIEW

**Comment by kohara260** [comment]
This only alters the design in the index.html file

**Comment by rocaplin** [comment]
The new design doesn't work with the chat widget. The hero image covers the chat widget. Also the bot's avatar is displayed incorrectly. I'll check to see what we can do to make the new design work with the chat widget.

**Comment by kohara260** [comment]
I did not alter the chat widget so that’s a bit strange

Best Regards,
Katriana O’Hara

Katriana L. O’Hara
Herbert Wertheim College of Engineering
University of Florida

________________________________

**Comment by kohara260** [comment]
I adjusted the webpage so the widget is not behind the hero image. I also added in Chris's bio

**Comment by rocaplin** [comment]
- The chat widget is incorrectly sized at various screen resolutions. The following should be added back to ui/src/App.css
```
.chat-window {
  /* interface font */
  font-family: 'Interface', sans-serif;
  max-width: 359px;
  height: calc(100% - 64px);
  border: solid 3px var(--grey-700);
  background-color: var(--grey-800);
  margin: 0 0 8px;
}

.chat-input {
  height: 64px;
  padding: 4px;
}
```

- The chatbot avatar is incorrectly sized. The following can be added to ui/src/components/chat-log/chat-log.styles.css

```
.avatar-container img {
  max-width: max-content;
}
```

**Comment by kohara260** [comment]
Incorporated changes suggested by Bob

**Comment by rocaplin** [comment]
Looks good. We should be able to merge.

**Pull request merged**
